name: wanderlab
favicon: null
layout_spectrum: 0.074076913530007
typography_spectrum: 0.49363311333581805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.021910745184868574
  lightness: 0.9272196181118488
  saturation: 0.7028556128498167
  rhythmicContrast: 0.646756874397397
purpose: []
